import torch
import torch.nn.functional as F
from torch import nn
from transformers import ClapModel, RobertaTokenizer


class ClapLoss(nn.Module):
    r"""
    Cosine-distance loss in the CLAP audio-text embedding space.

    Given CLAP audio embeddings of a waveform generated by MusicLDM and a text describing the
    target concept, returns `1 - cosine_similarity(audio_embeds, text_embeds)`, so that minimizing
    the loss pulls the generated audio towards the text.

    The text tower is frozen: gradients only flow back through `audio_embeds`.

    Args:
        text_encoder (`~transformers.ClapModel`): CLAP model used to embed the text. Typically the
            `text_encoder` of a `MusicLDMPipeline`, so that both sides live in the same embedding
            space as the pipeline's prompt embeddings.
        tokenizer (`~transformers.RobertaTokenizer`): Tokenizer matching `text_encoder`.
        reduction (`str`, *optional*, defaults to `"mean"`): How to reduce the per-item losses. One
            of `"mean"`, `"sum"` or `"none"`.
    """

    def __init__(
        self,
        text_encoder: ClapModel,
        tokenizer: RobertaTokenizer,
        reduction: str = "mean",
    ):
        super().__init__()

        if reduction not in ("mean", "sum", "none"):
            raise ValueError(f"`reduction` has to be one of 'mean', 'sum' or 'none' but is {reduction}")

        self.text_encoder = text_encoder
        self.tokenizer = tokenizer
        self.reduction = reduction

        # the text tower is only used to produce a fixed target embedding
        self.text_encoder.requires_grad_(False)
        self.text_encoder.eval()

    def encode_text(self, text: list[str]) -> torch.Tensor:
        r"""
        Embeds `text` with the CLAP text tower and L2-normalizes the result.

        Args:
            text (`list[str]`): The texts to embed.

        Returns:
            `torch.Tensor`: Normalized text embeddings of shape `(len(text), embed_dim)`.
        """
        device = next(self.text_encoder.parameters()).device

        text_inputs = self.tokenizer(
            text,
            padding="max_length",
            max_length=self.tokenizer.model_max_length,
            truncation=True,
            return_tensors="pt",
        )

        with torch.no_grad():
            text_embeds = self.text_encoder.get_text_features(
                text_inputs.input_ids.to(device),
                attention_mask=text_inputs.attention_mask.to(device),
            )

        # transformers >= 5 returns a `BaseModelOutputWithPooling`, earlier versions a plain tensor
        if not torch.is_tensor(text_embeds):
            text_embeds = text_embeds.pooler_output

        return F.normalize(text_embeds, dim=-1)

    def forward(self, audio_embeds: torch.Tensor, text: str | list[str]) -> torch.Tensor:
        r"""
        Args:
            audio_embeds (`torch.Tensor`): CLAP audio embeddings of shape `(batch_size, embed_dim)`.
            text (`str` or `list[str]`): The target concept(s). A single `str` is used for the whole
                batch, a list must match the batch size of `audio_embeds`.

        Returns:
            `torch.Tensor`: `1 - cosine_similarity`, reduced according to `reduction`. A scalar
            unless `reduction` is `"none"`, in which case the shape is `(batch_size,)`.
        """
        if audio_embeds.ndim != 2:
            raise ValueError(
                f"`audio_embeds` has to be of shape `(batch_size, embed_dim)` but has {audio_embeds.ndim} dimensions"
            )

        batch_size = audio_embeds.shape[0]

        if isinstance(text, str):
            texts = [text] * batch_size
        elif isinstance(text, list):
            if len(text) == 1:
                texts = text * batch_size
            elif len(text) != batch_size:
                raise ValueError(
                    f"`text` has batch size {len(text)}, but `audio_embeds` has batch size {batch_size}. Please make"
                    " sure that passed `text` matches the batch size of `audio_embeds`."
                )
            else:
                texts = text
        else:
            raise ValueError(f"`text` has to be of type `str` or `list` but is {type(text)}")

        text_embeds = self.encode_text(texts).to(device=audio_embeds.device, dtype=audio_embeds.dtype)

        cosine_similarity = (F.normalize(audio_embeds, dim=-1) * text_embeds).sum(dim=-1)
        loss = 1.0 - cosine_similarity

        if self.reduction == "mean":
            return loss.mean()
        if self.reduction == "sum":
            return loss.sum()
        return loss
